### ISSUE TITLE
Finish implementing Artists section in Zune Desktop Collection view

### ISSUE THREAD

**Issue by Arlodotexe** [Arlodotexe/strix-music#129]
# Background 
The "Artists" section in Zune Desktop is the default view when opening the Collection tab.

# The problem
Implementation of this view in Strix is incomplete.

# Solution
Finish implementing this view, making sure it's faithfully matches the original app. 

If you don't have the original app, the installer that we use is available [here](https://ipfs.io/ipfs/QmWWWeCSSE2xND9nLJG7PSJbQg2wHbpqebAzcSjYmfRrXu?filename=Zune%20Software%20v4.8.exe).

- [x] Implement default, basic collection columns (default view upon opening)
  - [x] Artist
  - [x] Albums
  - [x] Songs
- [x] Implement sorting Artists
- [x] Implement sorting Albums
- [x] Implement multi-artist song view when album is selected
- [ ] Implement multi-select
  - [ ] Display all albums on artist multi-select
  - [ ] Display all songs on album multi-select
- [x] Implement sorting of tracks (Fix tracks margins)
- [ ] Selecting artist with one album should auto-select the album
- [ ] Large album art when artist has single album
- [ ] Clicking number of items should select all items
- [ ] Clicking a group header should select all items in the group

**Comment by senolfndk** [comment]
can i download apps for windows

**Comment by senolfndk** [comment]
where can i download the app

**Comment by Arlodotexe** [comment]
> where can i download the app

Please don't post questions under random github issues. Try starting a [QnA Discussion](https://github.com/Arlodotexe/strix-music/discussions/categories/q-a) instead.

**Comment by senolfndk** [comment]
> > uygulamayı nereden indirebilirim
> 
> Lütfen rastgele github sorunları altında soru göndermeyin. Sorularınız varsa bunun yerine yeni bir [QnA Tartışması başlatmayı deneyin.](https://github.com/Arlodotexe/strix-music/discussions/categories/q-a)

excuse me sorry
