### ISSUE TITLE
Create build scripts

### ISSUE THREAD

**Issue by Arlodotexe** [Arlodotexe/strix-music#130]
# Background
In our [Pledges](https://github.com/Arlodotexe/strix-music#permanent), we promised:

> The entire project (docs, website, build process, dependencies, SDK, app, etc) are perpetually preserved in every released binary and on our website, all hosted on [IPFS](https://ipfs.io/). If anyone has these things, you'll be able to access it over IPFS

# Problem
In order to do this, we need to create build scripts that can perform all of our CI standalone, and put them in the repo.

# Solution
Create powershell scripts that can
 - [x] Apply git tags for a release
 - [x] Generates a changelog based on tags
 - [x] Generate the nuget package
 - [x] Generate documentation website
 - [x] Generate app releases (Wasm, Uwp)
 - [x] Generate strixmusic.com website
 - [x] Zip up the entire git repo
 - [x] Bundle it all together in a nice folder structure
 - [x] Include all these things as part of the git repo
